name: Deploy

on:
  push:
    branches:
      - main
  repository_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v1
      with:
        node-version: 16
    - run: sudo apt-get update && sudo apt-get install -y jq
    - run: yarn install
    - run: yarn build
      env:
        NODE_ENV: production
    - name: Publish
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        preCommands: |
          wrangler kv:namespace create KV_STATUS_PAGE || true
          KV_NAMESPACE_ID=$(wrangler kv:namespace list | jq -r '.[] | select(.title == "KV_STATUS_PAGE") | .id')
          echo "[env.production]" >> wrangler.toml
          echo "kv_namespaces = [{binding=\"KV_STATUS_PAGE\", id=\"${KV_NAMESPACE_ID}\"}]" >> wrangler.toml
          if [ -z "$SECRET_SLACK_WEBHOOK_URL" ]; then
            echo "Secret SECRET_SLACK_WEBHOOK_URL not set, creating dummy one..."
            export SECRET_SLACK_WEBHOOK_URL="default-gh-action-secret"
          fi
          if [ -z "$SECRET_TELEGRAM_API_TOKEN" ]; then
            echo "Secret SECRET_TELEGRAM_API_TOKEN not set, creating dummy one..."
            export SECRET_TELEGRAM_API_TOKEN="default-gh-action-secret"
          fi
          if [ -z "$SECRET_TELEGRAM_CHAT_ID" ]; then
            echo "Secret SECRET_TELEGRAM_CHAT_ID not set, creating dummy one..."
            export SECRET_TELEGRAM_CHAT_ID="default-gh-action-secret"
          fi
          if [ -z "$SECRET_DISCORD_WEBHOOK_URL" ]; then
            echo "Secret SECRET_DISCORD_WEBHOOK_URL not set, creating dummy one..."
            export SECRET_DISCORD_WEBHOOK_URL="default-gh-action-secret"
          fi
        postCommands: |
          yarn kv-gc
        secrets: |
          SECRET_SLACK_WEBHOOK_URL
          SECRET_TELEGRAM_API_TOKEN
          SECRET_TELEGRAM_CHAT_ID
          SECRET_DISCORD_WEBHOOK_URL
        environment: production
      env:
        CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        SECRET_SLACK_WEBHOOK_URL: ${{secrets.SECRET_SLACK_WEBHOOK_URL}}
        SECRET_TELEGRAM_API_TOKEN: ${{secrets.SECRET_TELEGRAM_API_TOKEN}}
        SECRET_TELEGRAM_CHAT_ID: ${{secrets.SECRET_TELEGRAM_CHAT_ID}}
        SECRET_DISCORD_WEBHOOK_URL: ${{secrets.SECRET_DISCORD_WEBHOOK_URL}}
